[[metric]]
context = "memory_pga"
fieldtoappend = "total_pga"
metricsdesc = { value= "Gauge metric of pga memory in use and allocated in MB." }
request = '''
select name as total_pga, round(value/1024/1024) as value
from v$pgastat
where name in ('total PGA allocated', 'total PGA inuse')
'''

[[metric]]
context = "memory_sga"
labels = [ "pool" ]
metricsdesc = { value= "Gauge metric of sga memory in use in MB." }
request = '''
select 'in_use' as overall, round(sum(bytes)/1024/1024) as value
from v$sgastat
where name not in ('KGH: NO ACCESS')
'''

[[metric]]
context = "sessions"
labels = [ "status", "type" ]
metricsdesc = { value= "Gauge metric with count of sessions by status and type." }
request = "SELECT status, type, COUNT(*) as value FROM v$session GROUP BY status, type"

[[metric]]
context = "sysmetrics"
fieldtoappend = "metric_name"
metricsdesc = { value= "Gauge various sysmetrics." }
request = '''
select metric_name, round(value) as value
from v$sysmetric
where group_id = 3
and metric_name in ('Database CPU Time Ratio', 'Average Active Sessions','Physical Reads Direct Per Sec','Physical Reads Per Sec','Logical Reads Per Sec','Consistent Read Gets Per Sec','Consistent Read Changes Per Sec')
'''

[[metric]]
context = "parameter"
labels = [ "name" ]
metricsdesc = { value= "Gauge initialization parameters currently in effect." }
request = '''
select name, value/1024/1024 as value
from v$parameter 
'''
